### ISSUE TITLE
No connect vpn Manager

### ISSUE THREAD

**Issue by muzaffer72** [jerry-bool/sail#11]
Hello ı have problem. 

2022-07-09 15:07:14.840 6847-6885/com.losgif.sail_app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method enableVPNManager on channel com.losgif.sail/vpn_manager)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
    <asynchronous suspension>
    #1      VpnManager.enableVPNManager (package:sail_app/channels/vpn_manager.dart:10:16)
    <asynchronous suspension>
    #2      AppModel.togglePowerButton (package:sail_app/models/app_model.dart:12:7)
    <asynchronous suspension>

My build Gradle. Default Setting for project

buildscript {
    ext.kotlin_version =  '1.6.10'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

**Comment by losgif** [comment]
wait for andorid side development.
